- README.md
- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/37)
> Closes softlayer/ember-style-guide#22

- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/38)
> Closes softlayer/ember-style-guide#17

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/39)
> Closes softlayer/ember-style-guide#16

- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/40)
> Closes softlayer/sl-ember-style-guide#18

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/41)
> Closes softlayer/ember-style-guide#15

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/42)
> Closes softlayer/ember-style-guide#28

- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/43)
> Closes softlayer/ember-style-guide#26

- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/44)
> Closes softlayer/ember-style-guide#34

- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/45)
> Closes softlayer/ember-style-guide#24

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/46)
> Closes softlayer/ember-style-guide#20

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/47)
> Closes softlayer/ember-style-guide#19

- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/48)
> Closes softlayer/ember-style-guide#12

- README.md
- javascript.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/49)
> Closes softlayer/ember-style-guide#27

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/52)
> Add rule regarding use of double quotes in templates

- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/53)
> Closes softlayer/ember-style-guide#51

- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/56)
> Closes softlayer/ember-style-guide#54

- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/57)
> Closes softlayer/ember-style-guide#55

- README.md
- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/70)
> Closes softlayer/ember-style-guide#68

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/71)
> Closes softlayer/ember-style-guide#58

- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/75)
> Closes softlayer/ember-style-guide#66

- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/76)
> Closes softlayer/ember-style-guide#65

- ember-testing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/softlayer/ember-style-guide/77)
> Closes softlayer/ember-style-guide#63
